ChangeKeyErr=Changing key error.
NotInitCrypt=Cipher was not initiated for encryption or decryption operation.
NotInitWrap=Cipher was not initiated for wrapping operation.
NotInitUnwrap=Cipher was not initiated for unwrapping operation.
InvalidKeyType=Invalid key type.
CryptErr=Error in execution of data encrypting/decrypting operation.
ModeNotSupp=Specified cipher mode not supported.
NoMode=No one mode was set or this cipher was already initiated.
NoIVUnwrap=IV is not set for execution of unwrapping operation.
NoIVDecrypt=IV is not set for execution of decrypting operation.
PaddingSet=Padding algorithm already was set.
PaddingNotSupp=Specified padding algorithm not supported.
InvEncryptMode=Invalid mode for execution of encrypting operation.
InvDecryptMode=Invalid mode for execution of decrypting operation.
UnwrapErr=Error in unwrapping key.
InvTextLen=Invalid total text length. It should be divisible by 8 bytes.
InvPar=Invalid parameters.
ImitaErr=Error in computing imita.
TransportSignKeyError=Signature key is not allowed for this operation.
NoCipherLicense=License doesn't permit cipher operations
ByteLimit=The limit of accepted bytes count is reached

