NotGostParam=Parameters are not conform to GOST R 34.10-2001 or GOST R 34.10-2012 algorithm
NotRSAParam=Parameters are not conform to RSA algorithm
NotECDSAParam=Parameters are not conform to ECDSA algorithm
NotSupported=Curve not supported
KoblitzNotSupported=Koblitz curve is not supported in this version of CryptPro CSP %s. Update CryptPro CSP to version %s or higher.
NotEDDSAParam=Parameters are not conform to EdDSA algorithm
NotEllipticParam=Parameters are not conform to GOST R 34.10-2001 or GOST R 34.10-2012 algorithm
InvalidCipherParam=Cipher params are not allowed for key pair generation
NullParam=Parameters are null
NotSupp=Method is not supported
KeyCreateError=Error in key creation
InvalidPublic=Public key is invalid
InvalidKeyLen=Invalid key length. Necessary number of bytes:
InvalidHashLen=Invalid length of master key hash
MasmatchParam=Parameters mismatch
WrapError=Error in wrapping key
UnwraprapError=Error in unwrapping key
KeyIsNotExportable=Key is not exportable
OldPasswordNeeded=Old password is needed
DiffAlgContainer=Cannot add key with different algorithm into existing container
DiffCipherAlgContainer=Cannot add key with different cipher parameters into existing container
KeyAlreadyExists=Key of this type already exists in container
KeyIsNotDhAllowed=Key is not allowed for this type of operation (DH)
InvalidPKUP=The private key has expired. A private key usage period cannot exceed 1 year 3 months
PKUPSpecNullDate=Time interval is 0 or less 0
PKUPSpecInvalidDate=Time interval is invalid, its value is too large
WarningWindowTitle=Warning
WarningWindowText=The GOST R 34.10-2001 keys will not be suitable <br> for signature generation since 01.01.2019. <br> Consider moving on GOST R 34.10-2012 keys.
ErrorLongMaterial=Encryption cannot be more used
UntrustedPubKey=Public key is untrusted
BadDiversAlg=GOST R 34.10-2012 key diversification using PRO_DIVERS algorithm is not allowed!
BadDiversData=Bad diversification data for the PRO_DIVERS algorithm!