license.option.serial={0} <serial>
license.option.company={0} <name>
license.annotation.serial=Product license.
license.annotation.company=Registered license company name.
invalid.library.hash=Invalid library hash! Expected %s but actual %s
