license.option.serial={0} <serial>
license.option.company={0} <name>
license.annotation.serial=Product license.
license.annotation.company=Registered license company name.
InValidSig=Can't verify signature of jar file!
install.check.signature=Check signature of module:
