NotGostParam=Parameters are not conform to GOST R 34.10-2001 or GOST R 34.10-2012 algorithm
NotRSAParam=Parameters are not conform to RSA algorithm
NotECDSAParam=Parameters are not conform to ECDSA algorithm
NotSupported=Curve not supported
KoblitzNotSupported=Koblitz curve is not supported in this version of CryptPro CSP %s. Update CryptPro CSP to version %s or higher.
NotEDDSAParam=Parameters are not conform to EdDSA algorithm
NotEllipticParam=Parameters are not conform to GOST R 34.10-2001 or GOST R 34.10-2012 algorithm
InvalidCipherParam=Cipher params are not allowed for key pair generation
NullParam=Parameters are null
NotSupp=Method is not supported
KeyCreateError=Error in key creation
InvalidPublic=Public key is invalid
InvalidKeyLen=Invalid key length. Necessary number of bytes:
InvalidHashLen=Invalid length of master key hash
MasmatchParam=Parameters mismatch
WrapError=Error in wrapping key
UnwraprapError=Error in unwrapping key
NotDHKey=Key parameters are not conform to GOST sign and Diffie-Hellman algorithms
BadDiversAlg=GOST R 34.10-2012 key diversification using PRO_DIVERS algorithm is not allowed!
BadDiversData=Bad diversification data for the PRO_DIVERS algorithm!
BadKey=Bad diversification key!
InvKeyType=Invalid key type
GenKeyErr=Unable create session key with specified parameters
