NeedEllipticKey=Key should conform to GOST R 34.10-2001 or GOST R 34.10-2012 algorithm
InvKeyType=Invalid key type
AlgNotMatch=Key algorithm does not match the signature algorithm.
InvKey=Invalid key value
InvParams=Invalid parameters
InvSigLen=Invalid length of signature
Updated=The data to be signed or verified was already updated
NotSupport=Method is not supported
NeedGenK=Parameter k should be regenerated
AlreadySigned=Signature already was created
OutOfRange=Invalid signature: out of range values