CLOSE_NOTIFY = "Close notify"
UNEXPECTED_MESSAGE = "Unexpected message"
BAD_RECORD_MAC = "Bad record mac"
DECRYPTION_FAILED = "Decryption failed"
RECORD_OVERFLOW = "Record overflow"
DECOMPRESSION_FAILURE = "Decompression failure"
HANDSHAKE_FAILURE = "Handshake failure"
NO_CERTIFICATE = "No certificate"
BAD_CERTIFICATE = "Bad certificate"
UNSUPPORTED_CERTIFICATE = "Unsupported certificate"
CERTIFICATE_REVOKED = "Certificate revoked"
CERTIFICATE_EXPIRED = "Certificate expired"
CERTIFICATE_UNKNOWN = "Certificate unknown"
ILLEGAL_PARAMETER = "Illegal parameter"
UNKNOWN_CA = "Unknown CA"
ACCESS_DENIED = "Access denied"
DECODE_ERROR = "Decode error"
DECRYPT_ERROR = "Decrypt error"
EXPORT_RESTRICTION = "Export Restriction"
PROTOCOL_VERSION = "Protocol version"
INSUFFICIENT_SECURITY = "Insufficient security"
INTERNAL_ERROR = "Internal error"
USER_CANCELED = "User canceled"
NO_RENEGOTIATION = "No renegotiation"
UNKNOWN_ALERT = "Unknown alert"