FullJTLS1=CryptoPro JTLS v.
ServSet=TLS Settings
ClnAuth=Client authentication
SessionCacheSize=Session cache size
SessionTime=Session keeping in a cache timeout (h)
SessionAmount=Allowed amount of sessions:
JTLSName= JTLS server
AUTH_NONE=not required
AUTH_REQUESTED=requested
AUTH_REQUIRED=required
ValidateChain=Check revocation status of the certificate chain
ValidateChainUsingCRLOnline=Load CRL by CRLDP (default)
ValidateChainUsingCRLOffline=Load CRL from directory
LicenseExpired=Current license expired. You should enter a new serial number.
RenegotiationIndication=Renegotiation indication
DisableRI=Allow unsafe renegotiation and legacy hello messages
EnableRI=Prohibit unsafe renegotiation, allow legacy hello messages
RequireRI=Prohibit unsafe renegotiation, require RFC 5746
DisableClientRI=Prohibit to client to send RI extension
SelectFile=Select file
open=Open