FullJCSP1=CryptoPro Java CSP v.
JCSPName=Java CSP
JCSPSettings=Java CSP Settings
FullJCSP2=(c) Crypto-Pro, 2005-
license.CSP=License type of CryptoPro CSP:
settings.panel.title=Select CSP names to configure default providers (need restart the control pane):
settings.panel.provider_2001=GOST R 34.10-2001 Signature with Diffie-Hellman Key Exchange
settings.panel.provider_2012_256=GOST R 34.10-2012 (256) Signature with Diffie-Hellman Key Exchange
settings.panel.provider_2012_512=GOST R 34.10-2012 (512) Signature with Diffie-Hellman Key Exchange
settings.panel.provider_RSA=RSA Signature and Key Exchange
settings.panel.provider_RSA.type=Type
settings.panel.provider_ECDSA=ECDSA Signature and Key Exchange
settings.panel.provider_EDDSA=EdDSA Signature
settings.panel.add.provider.name=<HTML>Split the list of containers by CryptoPro CSP providers that realize supported storage types.<BR>In this case the provider name will be added to the container name during the listing process (need to restart the control pane).</HTML>
license.loader.expired=The license of Java CSP has expired. Enter a new license.
settings.panel.keyset.title=Use key containers of (need restart the control pane):
settings.panel.keyset.user=user
settings.panel.keyset.machine=computer
settings.panel.name.title=Select containers by (need restart the control pane):
settings.panel.name.fqcn=friendly names
settings.panel.name.unique=unique names
reader.name=Reader:
reader.alias=Alias:
reader.providers=Providers:


