err.null.pass = Password can't be null.
err.no.key = Key can't be saved in certificate store.
err.null.pass.load.store = Operation failed. Store was loaded with null-password.
err.keyStore.format = Invalid key store format.
err.keyStore.err = Key store was tampered with, or password was incorrect.
err.big.cert = Certificate too big.
err.header.imit=Imita in the container header is wrong.
err.hash.alg=Hash algorithm of header is wrong.
err.hash.value=Hash value of header is wrong.
err.only.gost=Only GOST key algorithms are supported
err.sign.alg=Signature algorithm of header is wrong.
err.sign.value=Signature value of header is wrong.
err.mask.imit=Imita in the container mask is wrong.
err.need.pass=Need password.
err.no.need.pass=Password is not needed.
err.pass.invalid=Password is not valid.
err.invalid.pass.struct=Error in password structure.
