err.null.pass = Password can't be null.
err.no.key = Key can't be saved in certificate store.
err.null.pass.load.store = Operation failed. Store was loaded with null-password.
err.keyStore.format = Invalid key store format.
err.keyStore.err = Key store was tampered with, or password was incorrect.
err.big.cert = Certificate too big.
err.need.pass=Need password.
err.pass.invalid=Password is not valid.
