JCPnotInstall=Cryptoprovider CryptoPro JCP not installed.
StoreNotFound=Specified key store not found.
FileNotFound=Specified file not found.
StoreCorrupted=Specified key store is corrupted.
CertificateNotFound=Specified certificate not found.
KeyNotFound=Specified key not found.
IllegalArg=Illegal argument of command line.
OK=Program is passed successfully.
ValidSig=Signature is valid
InValidSig=Signature is invalid
Corrupt_1=Jar file is corrupted, manifest entries not found
Corrupt_2=Jar file is corrupted, wrong count of manifest entries
Corrupt_3=Jar file is corrupted, manifest entry not found:
Corrupt_4=Jar file is corrupted, invalid manifest entry
CorruptManifest=Manifest file is corrupted
InvDigest=Digest of Jar file content is absent or invalid.
VerifyJCP=Verifying signature of JCP.jar.
VerifyJCPASN=Verifying signature of JCP_ASN.jar.
VerifyASN=Verifying signature of asn1rt.jar.
SigAlg=Signature Algorithm:
PubKey=Public Key Info:
CertSubj=Certificate subject:
CertIss=Certificate issuer:
Signing=Signing Jar File...
Has16Sig=New signature couldn't be added, because there are already 16 valid signatures of Jar file.
HasValidSignWithCert=Valid signature of jar file for specified certificate already exists. There is nothing to do.
HasInValidSignWithCert=There is invalid signature of jar file for specified certificate. Deleting invalid signature....
NewSig=Creating new signature of jar file
VerifyBeforeSign=Verifying all exists signatures of jar file before signing...
VerifyAll=Verifying all exists signatures of jar file...
VerifyForCert=Verifying signature of jar file for specified certificate ...
NoSign=There is none signature of jar file
NoSignForCert=There is none signature of jar file for specified certificate
CountSign.1=from
CountSign.2=signatures of jar file are valid.
DelInv=Deleting all invalid signatures...
AfterDel=after deleting invalid signatures.
NoNeedSig=Necessary signature of jar file is absent.
incorrect_first_date=First installation date is incorrect
incorrect_cpu_amount=Too many CPUs/connections used
incorrect_id_hash=Serial number is incorrect
incorrect_product_type=Incorrect product type
incorrect_id_form=Serial number's form is incorrect
incorrect_run_out_of_time=License has expired
incorrect_id_server=It isn't server license
incorrect_id_crypto=License doesn't permit cryptographic operation
incorrect_license_version=Incorrect license version
unknown_cause=Unknown license exception
license.error=Error occurred during check of certificate license
license.not.found=License not found
license.check.failed=License check failed
license.check.failed.no_cert=License check failed. Certificate not found
encrypt.not.support=Encryption operations are not supported
InvalidCert=Invalid certificate (X.509)

