alreadyEntered.1= 
alreadyEntered.2=% has been already entered
BioFrameText=<HTML><CENTER>Move mouse pointer or press keys to generate<BR>a random sequence.</CENTER></HTML>
BioFrameTextMoveMouseLeft=Move cursor left.
BioFrameTextMoveMouseRight=Move cursor right.
BioFrameTitle=Random Generator Initialization
CPVerify.error.during.work=Error during store working
CPVerify.error.security.problem=Security problem in store
CPVerify.error.store.corrupted=Store corrupted
CPVerify.error.wrong.format=Wrong store format
pressEnterOrESCforCancel=Press Enter several times, or type ESC end press Enter for cancel
PRSGcorrupted=PRSG corrupted!
inputy.for=Input Y, if you agree, or some key, otherwise
security.level.1=Container's security level
security.level.2=higher than provider's one.
security.level.3=Rewrite container with
security.level.4=providers security level?
security.level.answer.yes=Accepted, because preferences.
security.level.answer.no=Declined, because preferences.