AltNameProcessor.UnknownExtension=Unknown Extension
AuthorityKeyIdentifierProcessor.names=Names
AuthorityKeyIdentifierProcessor.CertSerialNumber=Certificate Serial Number:
AuthorityKeyIdentifierProcessor.KeyID=KeyID
AuthorityKeyIdentifierProcessor.CertIssuer=Certificate Issuer
AuthorityKeyIdentifierProcessor.SerialNumber=Certificate Serial Number
BasicConstraintsProcessor.CAtrue=CA = true
BasicConstraintsProcessor.ChainLengthConstraints=Chain length:
BasicConstraintsProcessor.CAfalse=CA = false
CertificatePoliciesProcessor.qualifierID=Qualifier ID
CertificatePoliciesProcessor.qualifier=Qualifier
CertificatePoliciesProcessor.text=Text
CertificatePoliciesProcessor.organization=Organization
CertificatePoliciesProcessor.noticeNumbers=Notice Numbers
CertificatePoliciesProcessor.parameters=Parameters
CertificatePoliciesProcessor.policyIdentifier=Policy Identifier
CertificatePoliciesProcessor.qualifierName=Qualifier
CertificatePoliciesProcessor.qualifiers=Qualifiers
CertificatePoliciesProcessor.policy=Policy
CRLDistrbutionPointsProcessor.issuers=Issuers
CRLDistrbutionPointsProcessor.CRLDistrbutionPoint=CRL Distribution Point
GeneralNamesProcessor.country=Country
GeneralNamesProcessor.administrationDomainName=Administration Domain Name
GeneralNamesProcessor.privateDomainName=Private Domain Name
GeneralNamesProcessor.orgunit=Organization Unit
GeneralNamesProcessor.organizationUnits=Organization Units
personalName=Personal Name
GeneralNamesProcessor.userID=User ID
GeneralNamesProcessor.NetworkAddress=Network Address
GeneralNamesProcessor.extensionAttributes=Some Extension Attributes
GeneralNamesProcessor.domainDefinedAttributes=Domain Defined Attributes
GeneralNamesProcessor.nameAssigner=Name Assigner
GeneralNamesProcessor.name=Name
PrivateKeyUsagePeriodProcessor.validFrom=Valid from
PrivateKeyUsagePeriodProcessor.to= to
PrivateKeyUsagePeriodProcessor.validTo=Valid to
AuthorityInfoAccessProcessor.accessMethod=Access Method
AuthorityInfoAccessProcessor.accessDescription=Access Description
SMIMECapabilitiesProcessor.ObjID=Object Identificator
SMIMECapabilitiesProcessor.SMIMECapability=SMIME Capability
CertSrvCAVersion.cerIndex=Certificate Index
CertSrvCAVersion.keyIndex=Key Index
NetscapeCertTypeProcessor.bitNames.0=SSL Client
NetscapeCertTypeProcessor.bitNames.1=SSL Server
NetscapeCertTypeProcessor.bitNames.2=S/MIME
NetscapeCertTypeProcessor.bitNames.3=Object-signing
NetscapeCertTypeProcessor.bitNames.4=Reserved bit
NetscapeCertTypeProcessor.bitNames.5=SSL CA
NetscapeCertTypeProcessor.bitNames.6=S/MIME CA
NetscapeCertTypeProcessor.bitNames.7=Object-signing CA