NO_SIGNED=Certificate request is not signed yet
IS_SIGNED=Certificate request is already signed
ASN_ERROR=Parsing data error
CONNECT_ERROR=Connection error
NO_ALG_ERROR=Signature algorithm MUST be set for provider Java CSP RSA
INVALID_KEY_ALG_ERROR=Invalid private key algorithm: null
UNKNOWN_KEY_ALG_ERROR=Unknown private key algorithm