NotEllipticDHParam=Parameters are not conform to GOST R 34.10-2001 or GOST R 34.10-2012 and Diffie-Hellman algorithms
NotGost=Parameters are not conform to GOST R 34.10-94, GOST R 34.10-2001 or GOST R 34.10-2012 algorithm
GenKeyErr=Unable create session key with specified parameters
KeyCreateErr=Generating session key error.
NeedSV=Initialization should be executed with SV
NotDHKey=Key parameters are not conform to gost sign and Diffie-Hellman algorithms
NoCipherLicense=License doesn't permit cipher operations


