signature.form=Signatures
signature.form.signatures=List of signatures
signature.form.signer.name=Signer name
signature.form.signer.info=About signer
signature.table.nodata=No data
signature.table.name=Signer name
signature.table.email=EMail
signature.table.signing.date=Signing date
signature.main=Main
signature.additional=Additional
about.signature.format=Information about signature<br>with type %s
about.signature.valid=This signature is valid
about.signature.invalid=This signature is invalid
about.signature.signer=Signature signer
about.signature.signer.signed.attrs=Signed attributes
about.signature.signer.unsigned.attrs=Unsigned attributes
about.signature.signer.name=Name
about.signature.signer.email=Email
about.signature.signer.signing.date=Signing date
about.signature.signer.content.type=Content type
about.signature.signer.message.digest=Content type
about.signature.signer.cosigner=Counter signature
about.signature.signer.signing.cert=Signing certificate
about.signature.signer.signing.cert.v2=Signing certificate V2
about.signature.signer.signature.timestamp=Signature timestamp
about.signature.signer.certificate.refs=Certificate references
about.signature.signer.revocation.refs=Revocation references
about.signature.signer.certificate.values=Certificates
about.signature.signer.revocation.values=Revocation values
about.signature.signer.revocation.timestamp=Revocation timestamp
about.signature.signer.archive.timestamp.v3=Archive timestamp V3
about.signature.signer.certificate.cert=Certificate
about.signature.signer.reference.cert=Reference
about.signature.signer.reference.ocsp=OCSP reference
about.signature.signer.reference.crl=CRL reference
about.signature.signer.revocation.ocsp=OCSP response
about.signature.signer.revocation.crl=CRL list
about.signature.signer.hash.1.2.643.2.2.9=GOST R 34.11-94
about.signature.signer.hash.1.2.643.7.1.1.2.2=GOST R 34.11-2012 (256)
about.signature.signer.hash.1.2.643.7.1.1.2.3=GOST R 34.11-2012 (512)
about.signature.signer.sign.1.2.643.2.2.19=GOST R 34.10-2001
about.signature.signer.sign.1.2.643.7.1.1.1.1=GOST R 34.10-2012 (256)
about.signature.signer.sign.1.2.643.7.1.1.1.2=GOST R 34.10-2012 (512)
about.signature.signer.sign.1.2.643.2.2.98=GOST R 34.10-2001
about.signature.signer.sign.1.2.643.7.1.1.6.1=GOST R 34.10-2012 (256)
about.signature.signer.sign.1.2.643.7.1.1.6.2=GOST R 34.10-2012 (512)
about.signature.view.certificate=View certificate
about.signature.other.signers=Other signers
about.signature.about.signer=About signer
signature.container=Signature
signature.container.table.key=Key
signature.container.table.value=Value
signature.container.view.item=View
signature.container.save.item=Save to file...
button.ok=Ok
signer.version=Version
signer.owner=Owner
signer.serial=Serial number
signer.digest=Digest algorithm
signer.signature=Signature algorithm
signer.ocsp.valid=Valid
signer.ocsp.revoked=Revoked
signer.ocsp.unknown=Status is unknown